version: '3.8'

services:
  app:
    build: .
    container_name: database_sync_service
    ports:
      - "5665:8000"
    volumes:
      - ./config:/app/config
    environment:
      - PYTHONUNBUFFERED=1